import { HnlModuleItem, HnlWorkbench } from "../types/cad";

export const INITIAL_HNL_MODULES: HnlModuleItem[] = [
  {
    id: "mod_cad_core",
    name: "HNL CAD Core Engine",
    workbench: "HNL_CAD",
    description: "Vẽ và chỉnh sửa đối tượng CAD 2D/3D tốc độ cao, bắt điểm OSNAP và quản lý Layer.",
    version: "2026.1.0",
    isEnabled: true,
    isCore: true,
    author: "HNL CAD Engineering Team",
    tags: ["core", "draw", "modify", "layer"],
    memoryWeightMb: 12,
  },
  {
    id: "mod_ceiling",
    name: "HNL Ceiling Workbench",
    workbench: "HNL_CEILING",
    description: "Trần thạch cao chìm, trần nổi 600x600/600x1200, chia tấm 4 phương án, bố trí xương chính/phụ, ty treo và gia cường lỗ mở MEP.",
    version: "2026.1.2",
    isEnabled: true,
    isCore: false,
    author: "HNL Drywall Systems",
    tags: ["ceiling", "framing", "hanger", "grid", "gypsum"],
    memoryWeightMb: 18,
  },
  {
    id: "mod_wall",
    name: "HNL Wall & Fire Rating Workbench",
    workbench: "HNL_WALL",
    description: "Vách thạch cao nhiều lớp, Shaft Wall, vách cách âm STC, hệ chống cháy EI30 - EI120 có liên kết trực tiếp Tested Assembly Database.",
    version: "2026.1.2",
    isEnabled: true,
    isCore: false,
    author: "HNL Drywall Systems",
    tags: ["wall", "fire", "ei60", "ei120", "rockwool", "stud"],
    memoryWeightMb: 22,
  },
  {
    id: "mod_shopdrawing",
    name: "HNL Shopdrawing Automation",
    workbench: "HNL_SHOPDRAWING",
    description: "Tự động trích xuất mặt cắt, trích chi tiết cấu tạo (Auto Detail), đánh cốt cao độ và kiểm tra chất lượng Shopdrawing (HNL Shop Check).",
    version: "2026.1.0",
    isEnabled: true,
    isCore: false,
    author: "HNL Shopdrawing AI",
    tags: ["shopdrawing", "detail", "section", "audit", "dimension"],
    memoryWeightMb: 24,
  },
  {
    id: "mod_layout",
    name: "HNL Layout & Viewport Engine",
    workbench: "HNL_LAYOUT",
    description: "Tạo Sheet Layout A0-A4, căn chỉnh Viewport tự động, chọn tỷ lệ tối ưu 1:20 - 1:100, chèn Khung tên thông minh và xuất PDF/DWF.",
    version: "2026.1.0",
    isEnabled: true,
    isCore: false,
    author: "HNL Print & Publish",
    tags: ["layout", "viewport", "sheet", "a3", "titleblock"],
    memoryWeightMb: 14,
  },
  {
    id: "mod_quantity",
    name: "HNL Quantity & BOQ Builder",
    workbench: "HNL_QUANTITY",
    description: "Bóc tách khối lượng tự động từ Smart Object (diện tích tấm, mét dài khung xương, số lượng ty treo, bông Rockwool), xuất Excel công thức.",
    version: "2026.1.0",
    isEnabled: true,
    isCore: false,
    author: "HNL Quantity Takeoff",
    tags: ["boq", "quantity", "excel", "table", "material"],
    memoryWeightMb: 10,
  },
  {
    id: "mod_ai_copilot",
    name: "HNL AI Copilot & Natural Language",
    workbench: "HNL_AI",
    description: "Trợ lý AI CAD 9 bước (Request -> Context -> Intent -> Action -> Validate -> Preview -> User Confirm -> Execute -> Audit), hỗ trợ Offline Rules.",
    version: "2026.1.0",
    isEnabled: true,
    isCore: false,
    author: "HNL Antigravity AI",
    tags: ["ai", "copilot", "gemini", "natural language", "smart action"],
    memoryWeightMb: 28,
  },
  {
    id: "mod_automation_lisp",
    name: "HNL Automation & LISP Builder",
    workbench: "HNL_AUTOMATION",
    description: "Trình tạo mã AutoLISP/Visual LISP tự động, quản lý tệp .lsp, ghi lại quy trình thao tác CAD (Macro Recording) và phím tắt chuyên sâu.",
    version: "2026.1.0",
    isEnabled: true,
    isCore: false,
    author: "HNL AutoLISP Group",
    tags: ["lisp", "macro", "automation", "csharp", "plugin"],
    memoryWeightMb: 16,
  },
  {
    id: "mod_block_lib",
    name: "HNL Block & Smart Library",
    workbench: "HNL_BLOCK",
    description: "Thư viện Block động thông minh, tìm kiếm hình học tương đồng (Similarity AI), đếm số lượng và đồng bộ Dynamic Attributes.",
    version: "2026.1.0",
    isEnabled: true,
    isCore: false,
    author: "HNL Content Studio",
    tags: ["block", "dynamic block", "library", "architecture", "mep"],
    memoryWeightMb: 20,
  },
  {
    id: "mod_translate",
    name: "HNL Technical Drawing Translate",
    workbench: "HNL_TRANSLATE",
    description: "Dịch thuật ngữ bản vẽ kỹ thuật chuyên ngành (Việt - Anh - Trung), chế độ Bilingual Song Ngữ và bộ nhớ dịch Translation Memory.",
    version: "2026.1.0",
    isEnabled: true,
    isCore: false,
    author: "HNL Localization",
    tags: ["translate", "bilingual", "vietnamese", "english", "chinese"],
    memoryWeightMb: 15,
  },
];
