<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <AssemblyName>Hnl.CadBridge</AssemblyName>
    <Version>2.8.1</Version>
    <AssemblyVersion>2.8.1.0</AssemblyVersion>
    <FileVersion>2.8.1.0</FileVersion>
    <InformationalVersion>2.8.1</InformationalVersion>
    <RootNamespace>Hnl.CadBridge</RootNamespace>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AutoCAD.NET" Version="26.0.0" ExcludeAssets="runtime" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>
</Project>
