import fs from "node:fs";
import path from "node:path";

const root=process.cwd();
const read=(p)=>fs.readFileSync(path.join(root,p),"utf8");
const checks=[];
const check=(id,ok,detail)=>checks.push({id,ok:Boolean(ok),detail});
const app=read("src/App.tsx");
const canvas=read("src/components/Canvas/CadCanvas.tsx");
const diag=read("src/components/Dialogs/DiagnosticsModal.tsx");
const ribbon=read("src/components/Ribbon/HnlRibbon.tsx");
const nativeRibbon=read("autocad-plugin/Hnl.CadBridge/NativeRibbon.cs");
const nativePalette=read("autocad-plugin/Hnl.CadBridge/NativePalette.cs");
const bridge=read("autocad-plugin/Hnl.CadBridge/BridgeCommands.cs");
const electron=read("electron/main.cjs");
const server=read("server.ts");
const workflow=read(".github/workflows/build-windows.yml");
const ai=read("src/components/Dialogs/AiProviderManager.tsx");
const aiProviderCatalog=read("src/lib/aiProviderCatalog.ts");
const lispBuilder=read("src/components/Dialogs/LispBuilderModal.tsx");
const autoBridge=read("src/lib/autoCadBridge.ts");
const promptHits=[app,canvas,diag].reduce((n,x)=>n+(x.match(/window\.prompt\s*\(/g)||[]).length,0);
check("UI_NO_BROWSER_PROMPT",promptHits===0,`window.prompt hits=${promptHits}`);
check("START_CENTER_CLEAN",app.includes("Mở DWG bằng AutoCAD + HNL")&&app.includes("Mở DXF / Dự án HNL")&&app.includes("Tùy chọn DWG nâng cao"),"primary/advanced modes present");
check("DIRECT_DWG_GUARD",app.includes("đã bị chặn để tránh chỉnh Canvas giả"),"direct DWG local mutation guard");
check("SAVE_NATIVE",app.includes('SAVE_CURRENT_DWG')&&app.includes('SAVE_AS_DWG'),"native DWG save routes");
check("UNDO_REDO_NATIVE",app.includes('command:e.shiftKey?"REDO":"U"')&&app.includes('command:"REDO"'),"Ctrl+Z/Ctrl+Y native routes");
check("LAYOUT_SYNC_MODE",app.includes('}, [isNativeDwgWorkspace]);'),"layout mirror reacts to workspace mode");
check("BRIDGE_TIMEOUT_BUDGETS",autoBridge.includes("PUBLISH_LAYOUTS_PDF:180000")&&autoBridge.includes("ACTION_TIMEOUT_MS"),"action-specific timeout budgets");
check("BRIDGE_GOLDEN_GATE",server.includes("/api/autocad/golden-smoke")&&bridge.includes("_pollBusy")&&autoBridge.includes("/cancel"),"read-only runtime gate + overlap/deadline safety");
check("LISP_44_TAXONOMY",read("src/lib/lispFeatureCatalog.ts").match(/"sourceFile":/g)?.length===44,"44 exact sourceFile entries");
check("LISP_ON_DEMAND",bridge.includes("_lispAutoLoadEnabled = false")&&bridge.includes("LOAD_LISP_FILE"),"default on-demand");
check("TOOL_ARG_TAXONOMY",["BLOCK","LAYER","SHOPDRAWING"].every(x=>electron.includes(`'${x}'`)),"Electron accepts new taxonomy tool args");
check("NATIVE_PALETTE_TAXONOMY",nativePalette.includes("HNLBLOCK")&&nativePalette.includes("HNLLAYER")&&nativePalette.includes("HNLSHOP2D"),"palette routes all new centers");
check("NATIVE_RIBBON_TAXONOMY",nativeRibbon.includes('"Block / Attr"')&&nativeRibbon.includes('"Dim+"')&&nativeRibbon.includes('"Layer"'),"native ribbon current labels");
check("WEB_RIBBON_NO_DUP_SHOP",(ribbon.match(/>Smart Shopdrawing Platform<\/button>/g)||[]).length===1,"single Tools-menu entry");
check("LIBRARY_QUEUE",bridge.includes('CommandMethod("HNLINSERTPENDING"')&&bridge.includes("PendingLibraryInserts"),"non-blocking point prompt");
check("BOQ_NATIVE",bridge.includes('"GET_HNL_BOQ" => GetHnlBoq()'),"native tagged BOQ endpoint");
check("SHOP_AUDIT_NATIVE",bridge.includes('"AUDIT_HNL_SHOPDRAWING" => AuditHnlShopdrawing()'),"native shop audit endpoint");
check("AI_NO_SILENT_FALLBACK",aiProviderCatalog.includes("autoFallbackOffline:false")&&electron.includes("autoFallbackOffline: false")&&server.includes('HNL_AI_AUTO_FALLBACK_OFFLINE || "false"'),"fallback requires explicit opt-in");
check("AI_LISP_ONLINE_PAYLOAD",lispBuilder.includes("data?.lisp || (data?.code ? data : null)"),"online/offline payload normalized");
check("INSTALLER_PLUGIN",electron.includes("ApplicationPlugins")&&workflow.includes("Build AutoCAD plugins 2023-2027"),"one-click plugin path + build");
check("WORKFLOW_CURRENT_RIBBON",workflow.includes('"Block / Attr"')&&workflow.includes('"Dim+"')&&!workflow.includes('"Field Doctor","Quick Dim"'),"workflow gate matches current ribbon");
check("GENAI_PIN",JSON.parse(read("package.json")).dependencies?.["@google/genai"]==="2.4.0","@google/genai 2.4.0 pinned");
const failed=checks.filter(x=>!x.ok);
for(const x of checks) console.log(`${x.ok?"PASS":"FAIL"} ${x.id} — ${x.detail}`);
console.log(`HNL MASTER AUDIT STATIC: ${checks.length-failed.length}/${checks.length} PASS`);
if(failed.length) process.exit(1);
