import React,{useMemo,useState} from "react";
import { Activity, AlertTriangle, CheckCircle2, GitCompare, HeartPulse, ShieldCheck, Stethoscope, X } from "lucide-react";
import { CadEntity,CadLayer,CadLayout,CadViewport } from "../../types/cad";
import { applySafeDoctorFixes, inspectGeometry } from "../../lib/geometryDoctor";
import { compareDrawings } from "../../lib/drawingCompare";
import { loadCommandHealth } from "../../lib/commandHealth";
import { loadRecoveryGenerations } from "../../lib/recoveryGenerations";
import { runCoreSelfTests, SelfTestResult } from "../../lib/coreSelfTest";
import { loadRevisions, saveRevisionFromCompare, setRevisionStatus } from "../../lib/revisionManager";
import { RecoveryGeneration } from "../../lib/recoveryGenerations";

export const ProfessionalAuditCenterModal:React.FC<{
 isOpen:boolean;onClose:()=>void;entities:CadEntity[];layers:CadLayer[];layouts:CadLayout[];viewports:CadViewport[];
 onApplyEntities:(e:CadEntity[],msg:string)=>void;
 onRestoreSnapshot:(snapshot:any,label:string)=>void;
 onDiagnostic:(x:any)=>void;
}> = ({isOpen,onClose,entities,layers,layouts,viewports,onApplyEntities,onRestoreSnapshot,onDiagnostic})=>{
 const [tab,setTab]=useState<"DOCTOR"|"COMPARE"|"PUBLISH"|"HEALTH"|"RECOVERY">("DOCTOR");
 const [compareFile,setCompareFile]=useState<CadEntity[]|null>(null); const [selfTests,setSelfTests]=useState<SelfTestResult[]>([]);
 const [compareName,setCompareName]=useState("");
 const [revisionCode,setRevisionCode]=useState("A");
 const [revisionDesc,setRevisionDesc]=useState("");
 const revisions=useMemo(()=>loadRevisions(),[isOpen,tab,compareName]);
 const report=useMemo(()=>inspectGeometry(entities,layers,0.1),[entities,layers]);
 const health=useMemo(()=>loadCommandHealth(),[isOpen,tab]);
 const recovery=useMemo(()=>loadRecoveryGenerations(),[isOpen,tab]);
 if(!isOpen)return null;
 const fix=()=>{const next=applySafeDoctorFixes(entities,layers,report);const msg=`Safe Fix: ${entities.length} → ${next.length}; lỗi ${report.summary.errors}, cảnh báo ${report.summary.warnings}.`;if(window.confirm(`${msg}\n\nÁp dụng các fix an toàn?`)){onApplyEntities(next,msg);onDiagnostic({code:"HNL-DOCTOR-FIX",severity:"INFO",title:"Geometry Doctor Safe Fix",message:msg,command:"GEOMETRY_DOCTOR"});}};
 const openCompare=async(f:File)=>{try{const d=JSON.parse(await f.text());const arr=Array.isArray(d)?d:Array.isArray(d.entities)?d.entities:null;if(!arr)throw new Error("File không có entities hợp lệ.");setCompareFile(arr);setCompareName(f.name);}catch(e:any){onDiagnostic({code:"HNL-COMPARE-OPEN",severity:"ERROR",title:"Không đọc được file so sánh",message:e?.message||String(e),command:"DRAWING_COMPARE"});}};
 const cmp=compareFile?compareDrawings(compareFile,entities):null;
 return <div className="fixed inset-0 z-[198] bg-black/75 flex items-center justify-center p-3"><div className="w-full max-w-6xl h-[84vh] rounded-2xl border border-neutral-700 bg-[#17191d] shadow-2xl flex flex-col overflow-hidden">
 <div className="px-5 py-4 bg-[#111317] border-b border-neutral-800 flex justify-between"><div><div className="font-bold text-white flex gap-2 items-center"><Stethoscope className="w-5 h-5 text-cyan-400"/> HNL Professional Audit Center</div><div className="text-xs text-neutral-500 mt-1">Geometry Doctor • Drawing Compare • Command Health • Recovery Generations</div></div><button onClick={onClose}><X/></button></div>
 <div className="p-3 flex gap-1 border-b border-neutral-800">{[["DOCTOR","Geometry Doctor"],["COMPARE","Drawing Compare"],["PUBLISH","Publish Readiness"],["HEALTH","Command Health"],["RECOVERY","Recovery"]].map(([k,l])=><button key={k} onClick={()=>setTab(k as any)} className={`px-4 py-2 rounded text-sm ${tab===k?"bg-cyan-500 text-black":"bg-neutral-800 text-neutral-300"}`}>{l}</button>)}</div>
 <div className="p-5 overflow-auto flex-1">
 {tab==="DOCTOR"&&<div><div className="grid grid-cols-4 gap-3 mb-5"><Card k="Entities" v={report.summary.entities}/><Card k="Errors" v={report.summary.errors}/><Card k="Warnings" v={report.summary.warnings}/><Card k="Fixable" v={report.issues.filter(i=>i.fixable).length}/></div><button onClick={fix} className="mb-4 px-4 py-2 bg-emerald-500 text-black rounded font-semibold flex gap-2"><ShieldCheck className="w-4 h-4"/>Fix Safe Issues</button><div className="space-y-2">{report.issues.length===0?<div className="p-4 border border-emerald-800 bg-emerald-950/20 text-emerald-300 rounded flex gap-2"><CheckCircle2/>Không phát hiện lỗi Geometry Doctor hiện hỗ trợ.</div>:report.issues.slice(0,300).map(i=><div key={i.id} className={`p-3 border rounded ${i.severity==="ERROR"?"border-red-800 bg-red-950/20":"border-amber-800 bg-amber-950/20"}`}><div className="text-sm font-semibold text-neutral-200">{i.code} — {i.title}</div><div className="text-xs text-neutral-400 mt-1">{i.message}</div><div className="text-[10px] text-neutral-600 mt-1">{i.fixable?"Safe Fix available":"Review manually"} • {i.entityIds.join(", ")}</div></div>)}</div></div>}
 {tab==="COMPARE"&&<div className="space-y-4"><label className="block p-6 border-2 border-dashed border-neutral-700 rounded-xl text-center cursor-pointer"><GitCompare className="w-7 h-7 mx-auto text-cyan-400"/><div className="mt-2 text-sm text-neutral-300">{compareName||"Chọn file HNL JSON phiên bản trước"}</div><input type="file" accept=".json" className="hidden" onChange={e=>{const f=e.target.files?.[0];if(f)openCompare(f)}}/></label>{cmp&&<><div className="grid grid-cols-4 gap-3"><Card k="Added" v={cmp.added.length}/><Card k="Deleted" v={cmp.deleted.length}/><Card k="Modified" v={cmp.modified.length}/><Card k="Unchanged" v={cmp.unchanged}/></div><div className="p-4 rounded border border-neutral-800 bg-[#1d2025] text-sm text-neutral-300">So sánh dựa trên Link ID / Handle / ID và signature hình học.</div><div className="grid grid-cols-[100px_1fr_auto] gap-2 items-end"><label className="text-xs text-neutral-400">Revision<input value={revisionCode} onChange={e=>setRevisionCode(e.target.value)} className="mt-1 w-full p-2 rounded bg-neutral-900 border border-neutral-700"/></label><label className="text-xs text-neutral-400">Mô tả<input value={revisionDesc} onChange={e=>setRevisionDesc(e.target.value)} className="mt-1 w-full p-2 rounded bg-neutral-900 border border-neutral-700"/></label><button onClick={()=>{const x=saveRevisionFromCompare(revisionCode,revisionDesc,compareName,cmp);onDiagnostic({code:"HNL-REVISION-SAVE",severity:"INFO",title:"Đã lưu Revision",message:`${x.revision}: +${x.added} -${x.deleted} ~${x.modified}`,command:"REVISION_MANAGER"});setRevisionDesc("");}} className="px-3 py-2 rounded bg-cyan-500 text-black font-semibold text-xs">Lưu Revision</button></div>{revisions.length>0&&<div className="border border-neutral-800 rounded overflow-hidden"><div className="grid grid-cols-[80px_130px_1fr_90px_90px_90px_100px] bg-neutral-900 p-2 text-[10px] text-neutral-500"><span>Rev</span><span>Ngày</span><span>Mô tả</span><span>Added</span><span>Deleted</span><span>Modified</span><span>Status</span></div>{revisions.slice(0,30).map(r=><div key={r.id} className="grid grid-cols-[80px_130px_1fr_90px_90px_90px_100px] p-2 border-t border-neutral-800 text-xs"><span>{r.revision}</span><span>{new Date(r.createdAt).toLocaleDateString()}</span><span className="truncate">{r.description||r.sourceName}</span><span className="text-emerald-300">{r.added}</span><span className="text-red-300">{r.deleted}</span><span className="text-amber-300">{r.modified}</span><button onClick={()=>setRevisionStatus(r.id,r.status==="DRAFT"?"ISSUED":"DRAFT")} className={r.status==="ISSUED"?"text-emerald-300":"text-neutral-400"}>{r.status}</button></div>)}</div>}</>}</div>}
 {tab==="PUBLISH"&&<div>
  {(()=>{
    const checks=[
      {name:"Geometry Doctor",ok:report.summary.errors===0,detail:report.summary.errors===0?"Không có geometry error chặn.":`${report.summary.errors} geometry errors.`},
      {name:"Layout",ok:layouts.length>0,detail:layouts.length?`${layouts.length} layout(s).`:"Chưa có Layout."},
      {name:"Viewport lock",ok:viewports.length===0||viewports.every((v:any)=>v.locked),detail:viewports.length?`${viewports.filter((v:any)=>v.locked).length}/${viewports.length} viewport locked.`:"Không có Viewport."},
      {name:"Layer plot",ok:layers.some(l=>l.isPlottable!==false),detail:`${layers.filter(l=>l.isPlottable!==false).length}/${layers.length} layer plottable.`},
      {name:"Drawing content",ok:entities.length>0,detail:`${entities.length} entities.`},
    ];
    const bad=checks.filter(c=>!c.ok);
    return <><div className={`p-4 rounded-xl border ${bad.length?"border-amber-800 bg-amber-950/20":"border-emerald-800 bg-emerald-950/20"}`}><div className={`font-bold ${bad.length?"text-amber-300":"text-emerald-300"}`}>{bad.length?`NOT READY — ${bad.length} mục cần xử lý`:"READY FOR PUBLISH — kiểm tra nội bộ đạt"}</div><div className="text-xs text-neutral-500 mt-1">CTB/Page Setup/Xref/Font DWG native vẫn cần AutoCAD Bridge để xác nhận cuối.</div></div><div className="mt-4 space-y-2">{checks.map(c=><div key={c.name} className="p-3 rounded border border-neutral-800 bg-[#1d2025] flex items-center justify-between"><div><div className="text-sm text-neutral-200">{c.name}</div><div className="text-xs text-neutral-500 mt-1">{c.detail}</div></div><span className={c.ok?"text-emerald-300":"text-amber-300"}>{c.ok?"PASS":"CHECK"}</span></div>)}</div></>;
  })()}
 </div>}
 {tab==="HEALTH"&&<div><div className="flex items-center justify-between mb-3"><div className="text-sm text-neutral-400">Lịch sử command được ghi sau mỗi lần chạy từ v2.0.2.</div><button onClick={()=>setSelfTests(runCoreSelfTests())} className="px-3 py-2 rounded bg-cyan-500 text-black text-xs font-semibold">Run Core Self-Test</button></div>{selfTests.length>0&&<div className="mb-4 p-3 rounded border border-neutral-800 bg-[#1d2025]"><div className="text-xs font-semibold text-neutral-300 mb-2">Self-Test: {selfTests.filter(t=>t.status==="PASS").length}/{selfTests.length} PASS</div>{selfTests.map(t=><div key={t.name} className="grid grid-cols-[1fr_70px_90px_1.3fr] gap-2 text-xs py-1"><span>{t.name}</span><span className={t.status==="PASS"?"text-emerald-300":"text-red-300"}>{t.status}</span><span>{t.durationMs} ms</span><span className="text-neutral-500">{t.detail}</span></div>)}</div>}<div className="space-y-2">{Object.values(health).length===0?<div className="text-neutral-500">Chưa có dữ liệu. Hãy chạy các lệnh rồi mở lại tab này.</div>:Object.values(health).sort((a:any,b:any)=>(b.lastRunAt||"").localeCompare(a.lastRunAt||"")).map((h:any)=><div key={h.command} className="grid grid-cols-[1fr_100px_80px_110px_1.5fr] gap-3 items-center p-3 rounded border border-neutral-800 bg-[#1d2025] text-xs"><span className="text-neutral-200 font-mono">{h.command}</span><span className={h.status==="PASS"?"text-emerald-300":h.status==="FAIL"?"text-red-300":"text-amber-300"}>{h.status}</span><span>{h.runs} lần</span><span>{h.lastDurationMs??"-"} ms</span><span className="text-neutral-500 truncate">{h.lastError||"OK"}</span></div>)}</div></div>}
 {tab==="RECOVERY"&&<div><div className="text-sm text-neutral-400 mb-3">Tối đa 5 thế hệ Recovery gần nhất. Restore luôn hỏi xác nhận và thay workspace hiện tại.</div><div className="space-y-2">{recovery.length===0?<div className="text-neutral-500">Chưa có Recovery Generation.</div>:recovery.map((r:any,i:number)=><div key={r.savedAt} className="p-3 rounded border border-neutral-800 bg-[#1d2025] flex justify-between items-center"><div><div className="text-sm text-neutral-200">#{i+1} {r.label}</div><div className="text-xs text-neutral-500">{new Date(r.savedAt).toLocaleString()} • {r.snapshot?.entities?.length??0} entities</div></div><button onClick={()=>{if(window.confirm(`Khôi phục snapshot #${i+1} lúc ${new Date(r.savedAt).toLocaleString()}? Workspace hiện tại sẽ bị thay.`))onRestoreSnapshot(r.snapshot,`Recovery #${i+1}`)}} className="px-3 py-2 rounded bg-amber-500/15 border border-amber-700 text-amber-200 text-xs">Restore</button></div>)}</div></div>}
 </div></div></div>;
};
const Card:React.FC<{k:string;v:any}>=({k,v})=><div className="p-3 rounded border border-neutral-800 bg-[#1d2025]"><div className="text-[10px] uppercase text-neutral-600">{k}</div><div className="mt-1 text-xl font-bold text-neutral-100">{v}</div></div>;
