import React, { useMemo, useState } from "react";
import { ArrowRightLeft, Bot, CheckCircle2, Download, Eraser, FileUp, ShieldCheck, TriangleAlert, X } from "lucide-react";
import { CadEntity, CadLayer } from "../../types/cad";
import { auditForSketchUp, buildSketchUpBridgePackage, cleanup2D, CleanupOptions } from "../../lib/sketchUp2DBridge";
import { cadLinesToDxf, diffLinkIds, mapSuTagsRuleBased, projectSketchUpSceneTo2D, validateSuScenePackage } from "../../lib/sketchUpToCadEngine";

declare global { interface Window { electronNative?: any } }

type DiagnosticInput={code:string;severity:"INFO"|"WARNING"|"ERROR"|"CRITICAL";title:string;message:string;command?:string;suggestion?:string;context?:Record<string,unknown>};

export const SketchUp2DBridgeModal:React.FC<{
  isOpen:boolean; onClose:()=>void; entities:CadEntity[]; layers:CadLayer[]; selectedIds:string[];
  onApplyClean:(entities:CadEntity[], summary:string)=>void;
  onImportSketchUp:(entities:CadEntity[], layers:CadLayer[], summary:string)=>void;
  onDiagnostic:(e:DiagnosticInput)=>void;
}> = ({isOpen,onClose,entities,layers,selectedIds,onApplyClean,onImportSketchUp,onDiagnostic}) => {
  const [tab,setTab]=useState<"CLEAN"|"CAD_TO_SU"|"SU_TO_CAD"|"CHECK">("CLEAN");
  const [tol,setTol]=useState(0.1); const [tiny,setTiny]=useState(0.5); const [scope,setScope]=useState<"ALL"|"SELECTED">("ALL"); const [cleanupMode,setCleanupMode]=useState<"SAFE"|"STANDARD"|"AGGRESSIVE">("SAFE");
  const [suPackage,setSuPackage]=useState<any|null>(null); const [suFileName,setSuFileName]=useState("");
  const [aiMappings,setAiMappings]=useState<any[]>([]); const [aiBusy,setAiBusy]=useState(false);
  const issues=useMemo(()=>auditForSketchUp(scope==="SELECTED"?entities.filter(e=>selectedIds.includes(e.id)):entities,layers),[entities,layers,selectedIds,scope]);
  if(!isOpen)return null;

  const download=(name:string,text:string,type="application/json")=>{const a=document.createElement("a");const url=URL.createObjectURL(new Blob([text],{type}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
  const clean=()=>{try{const opts:CleanupOptions={toleranceMm:tol,removeDuplicates:true,removeTinySegments:cleanupMode!=="SAFE",tinySegmentMm:tiny,joinCollinearLines:cleanupMode!=="SAFE",flatten2D:true,normalizeLayers:true,removeNonPlotObjects:cleanupMode==="AGGRESSIVE"};const r=cleanup2D(entities,layers,opts);const summary=`${r.report.beforeCount} → ${r.report.afterCount}; trùng ${r.report.duplicateRemoved}; đoạn rác ${r.report.tinyRemoved}; join ${r.report.joinedLines}`;if(!window.confirm(`Preview Cleanup\n${summary}\n\nÁp dụng vào workspace? Hãy Save As file gốc trước khi làm sạch.`))return;onApplyClean(r.entities,summary);onDiagnostic({code:"HNL-CLEAN-OK",severity:"INFO",title:"2D Cleanup hoàn tất",message:summary,command:"CLEAN_2D",context:r.report});}catch(err:any){onDiagnostic({code:"HNL-CLEAN-ERR",severity:"ERROR",title:"2D Cleanup thất bại",message:err?.message||String(err),command:"CLEAN_2D",suggestion:"Không ghi đè file gốc. Copy Diagnostic Report và gửi kèm file mẫu."});}};
  const exportSU=()=>{try{if(scope==="SELECTED"&&!selectedIds.length)throw new Error("Chế độ Selected nhưng chưa chọn đối tượng.");const pkg=buildSketchUpBridgePackage(entities,layers,selectedIds,{scope,units:"mm",layerToTag:true,preserveColors:true,blocksToComponents:true,origin:"DRAWING_ORIGIN"});download("HNL_CAD_to_SketchUp.json",JSON.stringify(pkg,null,2));onDiagnostic({code:"HNL-SU-EXPORT-OK",severity:"INFO",title:"Đã tạo gói CAD → SketchUp",message:`Xuất ${pkg.geometry.length} đối tượng, ${pkg.tags.length} Tags. Dùng HNL CAD AI Bridge .rbz để Import/Update trong SketchUp.`,command:"EXPORT_SKETCHUP_2D",context:{warnings:pkg.warnings}});}catch(err:any){onDiagnostic({code:"HNL-SU-EXPORT-ERR",severity:"ERROR",title:"CAD → SketchUp thất bại",message:err?.message||String(err),command:"EXPORT_SKETCHUP_2D",suggestion:"Chạy Kiểm tra trước khi xuất; sửa geometry/layer lỗi rồi thử lại."});}};
  const loadSuFile=async(file:File)=>{try{const data=JSON.parse(await file.text());const errs=validateSuScenePackage(data);if(errs.length)throw new Error(errs.join(" "));setSuPackage(data);setSuFileName(file.name);setAiMappings([]);onDiagnostic({code:"HNL-SU2CAD-LOAD-OK",severity:"INFO",title:"Đã đọc gói SketchUp Scene",message:`${file.name}: ${data.edges?.length||0} edges, scene ${data.sceneName||"Current View"}.`,command:"IMPORT_SKETCHUP_SCENE"});}catch(err:any){setSuPackage(null);onDiagnostic({code:"HNL-SU2CAD-LOAD",severity:"ERROR",title:"Không đọc được gói SketchUp",message:err?.message||String(err),command:"IMPORT_SKETCHUP_SCENE",suggestion:"Xuất lại bằng HNL CAD AI Bridge .rbz rồi thử lại."});}};
  const projectSu=()=>{try{if(!suPackage)throw new Error("Chưa chọn file HNL SketchUp Scene JSON.");const p=projectSketchUpSceneTo2D(suPackage);
      if(aiMappings.length){
        const mm=new Map<string, any>(aiMappings.map((x:any): [string, any] => [String(x.tag), x]));
        p.entities=p.entities.map((e:any)=>{const map=mm.get(e.sourceTag);if(!map||e.sourceClass==="HIDDEN")return e;return{...e,layer:map.layer,color:map.color,lineweight:Number(map.lineweight)||e.lineweight};});
        for(const map of aiMappings){if(!p.layers.some(l=>l.name===map.layer))p.layers.push({name:map.layer,color:map.color||"#BFBFBF",lineweight:Number(map.lineweight)||0.13,linetype:"CONTINUOUS",isLocked:false,isVisible:true,isPlottable:true});}
      }
      const diff=diffLinkIds(entities,p.entities);const summary=`Scene ${suPackage.sceneName||"Current View"}: ${p.report.sourceEdges} edges → ${p.report.outputLines} line 2D; Hidden ${p.report.hidden}; section-crossing ${p.report.sectionCrossings}; diff +${diff.added} ~${diff.updated} -${diff.deleted} =${diff.unchanged}.`;if(!window.confirm(`${summary}\n\nImport/replace vào workspace HNL? Nên Save As trước.`))return;onImportSketchUp(p.entities,p.layers,summary);onDiagnostic({code:"HNL-SU2CAD-PROJECT-OK",severity:"INFO",title:"SketchUp → CAD 2D hoàn tất",message:summary,command:"PROJECT_SKETCHUP_TO_2D",context:{report:p.report,diff}});}catch(err:any){onDiagnostic({code:"HNL-SU2CAD-PROJECT",severity:"ERROR",title:"Projection SketchUp → CAD thất bại",message:err?.message||String(err),command:"PROJECT_SKETCHUP_TO_2D",suggestion:"Kiểm tra Scene/Camera; ưu tiên Parallel Projection; gửi JSON mẫu + Diagnostic Report."});}};
  const exportProjectedDxf=()=>{try{if(!suPackage)throw new Error("Chưa chọn file HNL SketchUp Scene JSON.");const p=projectSketchUpSceneTo2D(suPackage);if(aiMappings.length){const mm=new Map<string, any>(aiMappings.map((x:any): [string, any] => [String(x.tag), x]));p.entities=p.entities.map((e:any)=>{const map:any=mm.get(e.sourceTag);if(!map||e.sourceClass==="HIDDEN")return e;return{...e,layer:map.layer,color:map.color,lineweight:Number(map.lineweight)||e.lineweight};});for(const map of aiMappings){if(!p.layers.some(l=>l.name===map.layer))p.layers.push({name:map.layer,color:map.color||"#BFBFBF",lineweight:Number(map.lineweight)||0.13,linetype:"CONTINUOUS",isLocked:false,isVisible:true,isPlottable:true});}}const dxf=cadLinesToDxf(p.entities,p.layers,suPackage.sceneName||"SketchUp Scene");download(`HNL_${String(suPackage.sceneName||"SketchUp").replace(/[^A-Za-z0-9_-]+/g,"_")}_2D.dxf`,dxf,"application/dxf");onDiagnostic({code:"HNL-SU2CAD-DXF-OK",severity:"INFO",title:"Đã xuất DXF 2D",message:`${p.entities.length} entities từ Scene ${suPackage.sceneName||"Current View"}.`,command:"EXPORT_SKETCHUP_2D_DXF",context:p.report});}catch(err:any){onDiagnostic({code:"HNL-SU2CAD-DXF",severity:"ERROR",title:"Xuất DXF 2D thất bại",message:err?.message||String(err),command:"EXPORT_SKETCHUP_2D_DXF",suggestion:"Kiểm tra gói SketchUp, camera và geometry trước khi thử lại."});}};

  const aiSuggest=async()=>{try{if(!suPackage)throw new Error("Chưa có gói SketchUp.");setAiBusy(true);const tags=(suPackage.tags||[]).map((t:any)=>String(t.name||"")).filter(Boolean);const token=window.electronNative?.sessionToken||"";const res=await fetch("/api/gemini/sketchup-map",{method:"POST",headers:{"Content-Type":"application/json",...(token?{"x-hnl-token":token}:{})},body:JSON.stringify({tags})});const data=await res.json();const mappings=Array.isArray(data.mappings)&&data.mappings.length?data.mappings:mapSuTagsRuleBased(tags);setAiMappings(mappings);onDiagnostic({code:"HNL-SU2CAD-AI-MAP",severity:"INFO",title:"AI/Rule Layer Mapping",message:`Đã đề xuất mapping cho ${mappings.length} Tags. ${data.isOfflineFallback?"Rule-based offline":"AI online"}.`,command:"AI_SKETCHUP_LAYER_MAP"});}catch(err:any){const tags=(suPackage?.tags||[]).map((t:any)=>String(t.name||"")).filter(Boolean);const fallback=mapSuTagsRuleBased(tags);setAiMappings(fallback);onDiagnostic({code:"HNL-SU2CAD-AI-FALLBACK",severity:"WARNING",title:"AI mapping không khả dụng",message:`${err?.message||err}. Đã dùng rule-based fallback.`,command:"AI_SKETCHUP_LAYER_MAP"});}finally{setAiBusy(false);}};

  return <div className="fixed inset-0 z-[195] bg-black/75 flex items-center justify-center p-3"><div className="w-full max-w-6xl h-[84vh] bg-[#17191d] border border-neutral-700 rounded-2xl shadow-2xl overflow-hidden flex flex-col">
    <div className="px-5 py-4 bg-[#111317] border-b border-neutral-800 flex justify-between"><div><div className="font-bold text-white flex gap-2 items-center"><ArrowRightLeft className="w-5 h-5 text-cyan-400"/> CAD 2D ⇄ SketchUp Bridge</div><div className="text-xs text-neutral-500 mt-1">2 chiều: Cleanup, CAD→SketchUp, SketchUp Scene/Section→CAD 2D, Link ID/diff và AI gợi ý layer.</div></div><button onClick={onClose}><X/></button></div>
    <div className="flex gap-1 p-3 border-b border-neutral-800">{[["CLEAN","Làm sạch 2D"],["CAD_TO_SU","CAD → SketchUp"],["SU_TO_CAD","SketchUp → CAD"],["CHECK","Preflight"]].map(([k,l])=><button key={k} onClick={()=>setTab(k as any)} className={`px-4 py-2 rounded text-sm ${tab===k?"bg-cyan-500 text-black":"bg-neutral-800 text-neutral-300"}`}>{l}</button>)}</div>
    <div className="p-6 overflow-auto flex-1">
      {tab==="CLEAN"&&<div className="space-y-4"><div className="mb-3"><label className="text-sm text-neutral-300">Mức Cleanup <select value={cleanupMode} onChange={e=>setCleanupMode(e.target.value as any)} className="ml-3 bg-neutral-900 border border-neutral-700 rounded p-2"><option value="SAFE">Safe — chỉ xử lý chắc chắn</option><option value="STANDARD">Standard — thêm đoạn rác + Join</option><option value="AGGRESSIVE">Aggressive — mạnh, cần kiểm tra kỹ</option></select></label></div><div className="grid grid-cols-2 gap-4"><label className="text-sm text-neutral-300">Tolerance (mm)<input type="number" value={tol} onChange={e=>setTol(Number(e.target.value))} className="mt-1 w-full bg-neutral-900 border border-neutral-700 rounded p-2"/></label><label className="text-sm text-neutral-300">Đoạn rác nhỏ hơn (mm)<input type="number" value={tiny} onChange={e=>setTiny(Number(e.target.value))} className="mt-1 w-full bg-neutral-900 border border-neutral-700 rounded p-2"/></label></div><div className="p-4 bg-amber-950/20 border border-amber-800 rounded text-sm text-amber-200"><ShieldCheck className="inline w-4 h-4 mr-2"/>Cleanup luôn Preview + Confirm. Không ghi đè file CAD/SKP nguồn.</div><button onClick={clean} className="px-4 py-2 bg-cyan-500 text-black font-semibold rounded flex gap-2"><Eraser className="w-4 h-4"/>Preview & Apply Cleanup</button></div>}
      {tab==="CAD_TO_SU"&&<div className="space-y-4"><label className="text-sm text-neutral-300">Phạm vi<select value={scope} onChange={e=>setScope(e.target.value as any)} className="ml-3 bg-neutral-900 border border-neutral-700 rounded p-2"><option value="ALL">Toàn Model</option><option value="SELECTED">Đối tượng đang chọn ({selectedIds.length})</option></select></label><div className="p-4 bg-[#1d2025] border border-neutral-800 rounded text-sm text-neutral-300">Xuất JSON vector có Link ID. Trong SketchUp cài <b>HNL CAD AI Bridge v2.7.2.rbz</b> rồi chọn Extensions → HNL CAD AI Bridge → Import/Update HNL CAD → SketchUp.</div><button onClick={exportSU} className="px-4 py-2 bg-emerald-500 text-black font-semibold rounded flex gap-2"><Download className="w-4 h-4"/>Tạo gói CAD → SketchUp</button></div>}
      {tab==="SU_TO_CAD"&&<div className="space-y-5"><div className="p-4 bg-violet-950/20 border border-violet-800 rounded text-sm text-violet-200">Trong SketchUp: cài `.rbz` → chọn Scene/Section → Extensions → HNL CAD AI Bridge → <b>Export Scene/Section → HNL CAD</b>. Nên dùng Parallel Projection cho bản vẽ kỹ thuật.</div><label className="block border-2 border-dashed border-neutral-700 rounded-xl p-6 text-center hover:border-cyan-700 cursor-pointer"><FileUp className="w-7 h-7 mx-auto text-cyan-400"/><div className="mt-2 text-sm text-neutral-300">{suFileName||"Chọn HNL_SketchUp_Scene.json"}</div><input type="file" accept=".json,application/json" className="hidden" onChange={e=>{const f=e.target.files?.[0];if(f)loadSuFile(f);}}/></label>{suPackage&&<><div className="grid grid-cols-4 gap-3 text-sm"><Info k="Scene" v={suPackage.sceneName||"Current View"}/><Info k="Edges" v={String(suPackage.edges?.length||0)}/><Info k="Tags" v={String(suPackage.tags?.length||0)}/><Info k="Camera" v={suPackage.camera?.perspective?"Perspective":"Parallel/Ortho"}/></div><div className="flex gap-2"><button onClick={projectSu} className="px-4 py-2 bg-cyan-500 text-black font-semibold rounded">Project → CAD 2D</button><button onClick={exportProjectedDxf} className="px-4 py-2 bg-emerald-500 text-black font-semibold rounded">Xuất DXF 2D</button><button onClick={aiSuggest} disabled={aiBusy} className="px-4 py-2 bg-violet-500/20 border border-violet-700 text-violet-200 rounded flex items-center gap-2"><Bot className="w-4 h-4"/>{aiBusy?"Đang phân tích...":"AI gợi ý Layer/Nét"}</button></div>{aiMappings.length>0&&<div className="border border-neutral-800 rounded overflow-hidden"><div className="grid grid-cols-4 bg-neutral-900 text-xs text-neutral-500 px-3 py-2"><span>SketchUp Tag</span><span>CAD Layer</span><span>Lineweight</span><span>Lý do</span></div>{aiMappings.slice(0,50).map((m:any,i)=><div key={i} className="grid grid-cols-4 px-3 py-2 border-t border-neutral-800 text-xs text-neutral-300"><span>{m.tag}</span><span className="text-cyan-300">{m.layer}</span><span>{m.lineweight}</span><span className="text-neutral-500">{m.reason||"AI suggestion"}</span></div>)}</div>}</>}</div>}
      {tab==="CHECK"&&<div><div className="mb-4 text-sm text-neutral-400">CAD hiện tại: {scope==="SELECTED"?selectedIds.length:entities.length} đối tượng • {layers.length} Layer</div>{issues.length===0?<div className="p-4 border border-emerald-800 bg-emerald-950/20 text-emerald-300 rounded flex gap-2"><CheckCircle2/>Không phát hiện lỗi chặn CAD → SketchUp.</div>:<div className="space-y-2">{issues.map((i,idx)=><div key={idx} className={`p-3 rounded border ${i.severity==="ERROR"?"border-red-800 bg-red-950/20 text-red-300":"border-amber-800 bg-amber-950/20 text-amber-200"}`}><TriangleAlert className="inline w-4 h-4 mr-2"/><b>{i.code}</b> — {i.message}</div>)}</div>}<div className="mt-5 p-4 border border-neutral-800 rounded text-sm text-neutral-400">SketchUp → CAD: TRUE section-cut contour và occlusion hidden-line chính xác vẫn là phần khó. Từ v2.3.0 HNL không giả nhận `sectionCrossing` là đường CUT; nó chỉ ghi metadata để phát triển classifier chính xác hơn.</div></div>}
    </div></div></div>;
};
const Info:React.FC<{k:string;v:string}>=({k,v})=><div className="p-3 bg-[#1d2025] border border-neutral-800 rounded"><div className="text-[10px] uppercase text-neutral-600">{k}</div><div className="mt-1 text-neutral-200 truncate">{v}</div></div>;
