<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <Deterministic>true</Deterministic>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <Company>HNL Tool</Company>
    <Product>HNL Tool - VXT Pro</Product>
    <Authors>HNL Tool</Authors>
    <Copyright>Copyright © HNL Tool 2026</Copyright>
    <VersionPrefix>7.0.0</VersionPrefix>
    <VersionSuffix>alpha.4</VersionSuffix>
    <AssemblyVersion>7.0.0.4</AssemblyVersion>
    <FileVersion>7.0.0.4</FileVersion>
  </PropertyGroup>
</Project>
